// <auto-generated />
namespace Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class changeId_addFullname : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(changeId_addFullname));
        
        string IMigrationMetadata.Id
        {
            get { return "202405121230065_changeId_addFullname"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
